<?php
/*
 * Mall Only CONSTANTS file
 */

define('FORBIZCONTROLLERPATH', CORE_MALL_ROOT.DIRECTORY_SEPARATOR.'controller'.DIRECTORY_SEPARATOR);
define('FORBIZMODELPATH', CORE_MALL_ROOT.DIRECTORY_SEPARATOR.'model'.DIRECTORY_SEPARATOR);
define('CUSTOMCONTROLLERPATH', CUSTOM_ROOT.DIRECTORY_SEPARATOR.'controller'.DIRECTORY_SEPARATOR);
define('CUSTOMMODELPATH', CUSTOM_ROOT.DIRECTORY_SEPARATOR.'model'.DIRECTORY_SEPARATOR);
